import 'package:brew_path/shared/repositories/bank_envelope.dart';
import 'package:brew_path/shared/repositories/content_assembly.dart';
import 'package:flutter_test/flutter_test.dart';

/// Proves what makes a generated bank's envelope usable, and that every way it
/// can be unusable is refused by name rather than read past.
///
/// These are build defects — the banks ship inside the app — so the assertions
/// are all about refusing loudly, not about recovering.
void main() {
  const asset = 'assets/content/generated/lessons.json';

  Map<String, dynamic> envelope({
    Object? version = contentSchemaVersion,
    Object? items = const [
      {'id': 'a'},
    ],
  }) => {
    'generated': 'Generated by tool/extract_content.js',
    'source': 'data.jsx',
    'bank': 'lessons',
    if (version != null) 'schemaVersion': version,
    if (items != null) 'items': items,
  };

  group('a bank at the expected version', () {
    test('yields its records', () {
      final records = bankRecords(envelope(), assetPath: asset);

      expect(records, [
        {'id': 'a'},
      ]);
    });

    test('yields every record, in the order written', () {
      final records = bankRecords(
        envelope(
          items: const [
            {'id': 'a'},
            {'id': 'b'},
            {'id': 'c'},
          ],
        ),
        assetPath: asset,
      );

      expect(records.map((record) => record['id']), ['a', 'b', 'c']);
    });
  });

  group('a version the build was not written against is refused', () {
    test('a newer bank throws', () {
      expect(
        () => bankRecords(
          envelope(version: contentSchemaVersion + 1),
          assetPath: asset,
        ),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an older bank throws', () {
      expect(
        () => bankRecords(
          envelope(version: contentSchemaVersion - 1),
          assetPath: asset,
        ),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('the refusal names the asset and both versions', () {
      Object? thrown;
      try {
        bankRecords(envelope(version: 99), assetPath: asset);
      } on ContentFormatException catch (error) {
        thrown = error;
      }

      // Whoever reads this line has to tell, without opening anything, whether
      // the bank is stale or the app is.
      expect(
        '$thrown',
        allOf(
          contains(asset),
          contains('99'),
          contains('$contentSchemaVersion'),
        ),
      );
    });

    test('an unstamped bank throws rather than defaulting', () {
      // This is exactly the output that shipped before the version existed, so
      // absence has to fail — treating it as "probably fine" would wave through
      // the one case the version was added to catch.
      expect(
        () => bankRecords(envelope(version: null), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('a version that is not a number throws', () {
      expect(
        () => bankRecords(envelope(version: '1'), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });

  group('an envelope that is not a bank is refused', () {
    test('a decoded list throws', () {
      expect(
        () => bankRecords(const [], assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('a decoded scalar throws', () {
      expect(
        () => bankRecords('nonsense', assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('null throws', () {
      expect(
        () => bankRecords(null, assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });

  group('a bank carrying no usable records is refused', () {
    test('a missing item list throws', () {
      expect(
        () => bankRecords(envelope(items: null), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an empty item list throws', () {
      // A course that loads cleanly with nothing in it is the failure nobody
      // notices until a learner opens a tab and finds it bare.
      expect(
        () => bankRecords(envelope(items: const []), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an item list that is not a list throws', () {
      expect(
        () => bankRecords(envelope(items: 'nope'), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });
}
