import 'package:brew_path/shared/repositories/bank_envelope.dart';
import 'package:brew_path/shared/repositories/content_assembly.dart';
import 'package:flutter_test/flutter_test.dart';

/// Proves what makes a generated bank's envelope usable, and that every way it
/// can be unusable is refused by name rather than read past.
///
/// These are build defects — the banks ship inside the app — so the assertions
/// are all about refusing loudly, not about recovering.
void main() {
  const asset = 'assets/content/generated/lessons.json';

  Map<String, dynamic> envelope({
    Object? version = contentSchemaVersion,
    Object? items = const [
      {'id': 'a'},
    ],
  }) => {
    'generated': 'Generated by tool/extract_content.js',
    'source': 'data.jsx',
    'bank': 'lessons',
    // Null-aware so a case can drop a key entirely, which is what an
    // unstamped or item-less bank actually looks like on disk.
    'schemaVersion': ?version,
    'items': ?items,
  };

  group('a bank at the expected version', () {
    test('yields its records', () {
      final records = bankRecords(envelope(), assetPath: asset);

      expect(records, [
        {'id': 'a'},
      ]);
    });

    test('yields every record, in the order written', () {
      final records = bankRecords(
        envelope(
          items: const [
            {'id': 'a'},
            {'id': 'b'},
            {'id': 'c'},
          ],
        ),
        assetPath: asset,
      );

      expect(records.map((record) => record['id']), ['a', 'b', 'c']);
    });
  });

  group('a version the build was not written against is refused', () {
    test('a newer bank throws', () {
      expect(
        () => bankRecords(
          envelope(version: contentSchemaVersion + 1),
          assetPath: asset,
        ),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an older bank throws', () {
      expect(
        () => bankRecords(
          envelope(version: contentSchemaVersion - 1),
          assetPath: asset,
        ),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('the refusal names the asset and both versions', () {
      // Whoever reads this line has to tell, without opening anything, whether
      // the bank is stale or the app is. Asserted as whole phrases: a bare
      // match on the number would pass on a message that printed any stray 1.
      expect(
        () => bankRecords(envelope(version: 99), assetPath: asset),
        throwsA(
          isA<ContentFormatException>().having(
            (error) => error.message,
            'message',
            allOf(
              contains(asset),
              contains('carries schemaVersion 99'),
              contains('this build reads schemaVersion $contentSchemaVersion'),
            ),
          ),
        ),
      );
    });

    test('an unstamped bank is refused, and says so in those words', () {
      // This is exactly the output that shipped before the version existed, so
      // absence has to fail — treating it as "probably fine" would wave through
      // the one case the version was added to catch. It is also the refusal a
      // genuinely stale build produces, so the wording is worth pinning.
      expect(
        () => bankRecords(envelope(version: null), assetPath: asset),
        throwsA(
          isA<ContentFormatException>().having(
            (error) => error.message,
            'message',
            contains('carries no schemaVersion'),
          ),
        ),
      );
    });

    test('a version that is not a number throws', () {
      expect(
        () => bankRecords(envelope(version: '1'), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('a version that decoded as a double throws', () {
      // `1.0 == 1` is true of Dart's numbers, so without a type check this
      // would pass while the string '1' above is refused — an inconsistency
      // that would only ever show up in a hand-edited bank.
      expect(
        () => bankRecords(envelope(version: 1.0), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });

  group('an envelope that is not a bank is refused', () {
    test('a decoded list throws', () {
      expect(
        () => bankRecords(const [], assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('a decoded scalar throws', () {
      expect(
        () => bankRecords('nonsense', assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('null throws', () {
      expect(
        () => bankRecords(null, assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });

  group('a bank carrying no usable records is refused', () {
    test('a missing item list throws', () {
      expect(
        () => bankRecords(envelope(items: null), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an empty item list throws', () {
      // A course that loads cleanly with nothing in it is the failure nobody
      // notices until a learner opens a tab and finds it bare.
      expect(
        () => bankRecords(envelope(items: const []), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });

    test('an item list that is not a list throws', () {
      expect(
        () => bankRecords(envelope(items: 'nope'), assetPath: asset),
        throwsA(isA<ContentFormatException>()),
      );
    });
  });
}
